apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-rpc-server-start-config
data:
  discovery.yml: |
    serviceBinaries:
      admin-rpc: 1
    toolBinaries:
      - check-component
      - attribute-to-credential
    maxFileDescriptors: 10000
