apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-api-server-start-config
data:
  discovery.yml: |
    serviceBinaries:
      bot-api: 1
    toolBinaries:
      - check-component
      - attribute-to-credential
    maxFileDescriptors: 10000
