apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-rpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-rpc-server
  template:
    metadata:
      labels:
        app: bot-rpc-server
    spec:
      containers:
        - name: openim-bot-rpc-container
          image: openim/openim-bot-rpc:v3.8.3
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: CHATENV_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
            - name: IMENV_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: openim-mongo-secret
                  key: mongo_openim_username
            - name: CHATENV_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_openim_password

          volumeMounts:
            - name: openim-chat-config
              mountPath: "/config"
              readOnly: true
            - mountPath: /openim-chat/start-config.yml
              name: start-config
              subPath: start-config.yml
          ports:
            - containerPort: 30400
      volumes:
        - name: openim-chat-config
          configMap:
            name: openim-chat-config
        - name: start-config
          configMap:
            name: bot-rpc-server-start-config
