apiVersion: v1
kind: Service
metadata:
  name: bot-api-service
spec:
  selector:
    app: bot-api-server
  ports:
    - name: bot-api-10010
      protocol: TCP
      port: 10010
      targetPort: 10010
  type: ClusterIP
